// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestAppLibrary.Data;

#nullable disable

namespace TestAppLibrary.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20220304144036_StartWithDummy")]
    partial class StartWithDummy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("TestAppLibrary.Data.Models.Dummy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dummies");
                });
#pragma warning restore 612, 618
        }
    }
}
